language: node_js
node_js:
- 4.2.3
install:
- npm test
deploy:
  provider: npm
  email: npm@smart-coordination.com
  api_key:
    secure: i+v5PmcuTN8qvCKJ732IhAJmquVZJjIXmVtQ4+Hd2iZyz+UWpNukkdawzd7K3Te8s7VpQlDUIjoqobXOBmN2aG/fjGb88dawqDYyyUkhkp1dP6MN5LEUrz/UQV11s8K6aoZHDGp9RslhYbLtJBuUrA5nPvR6iWEMA74dfhvGnT+pMCNCayyKNzXVgzJaz5IoKBIWle8Ho01WgySNnC5BgIGmEzw1uS+NY9rPWxB2WWp+tyVwt2KPHIQDw+aiRK7ZXamQaydHEszrUnbTdBgknEujvBuw+gAnAUDtQKLU9+QlDplELSk/6ZJHdmqjH3tbY83CxGdf3MEPP3zPeEWd+lK4rG8x3y+i+R9N2SC/b62EB47TuxqXlrR7c5NbV5ntlg26d3PxgYliHSe8DbQA7BiUF5+P41CJ93B8WC9YTc+h0YPnkAX+YHzPbjrwIbvao8513VylkaiCtP8KBBKClLR0KlEv0uslWhMcT5McyqIJV9H4fR33I1evBdSTs1kjpiH6mfBuk0/IpM1pY0d8gTJ34pSQLm7Fu29NuYjbf8cjxi+9cGClYLhqGU4n8R/kE4b6Qy615ou/KuvY3D+10bqIvlqljyTjLHc7X0Qlr9HViGOzWv/GaQ9kGRzG9+ueW1ERybfwY4YJWsQVFbsW0ljpLOugAXnJHSC+OL6x1o4=
  on:
    repo: GitZoneTools/c9config
